student@student-Standard-PC-i440FX-PIIX-1996:~/Desktop/Project$ ansible-playbook -i Inventory.yaml AddUserAccounts.yaml -vvv
ansible-playbook [core 2.13.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/student/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/student/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.10 (default, Sep 11 2024, 16:02:53) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/student/Desktop/Project/Inventory.yaml as it did not pass its verify_file() method
script declined parsing /home/student/Desktop/Project/Inventory.yaml as it did not pass its verify_file() method
Parsed /home/student/Desktop/Project/Inventory.yaml inventory source with yaml plugin
[WARNING]: Collection vyos.vyos does not support Ansible version 2.13.13
redirecting (type: modules) ansible.builtin.win_user to ansible.windows.win_user
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: AddUserAccounts.yaml *************************************************
3 plays in AddUserAccounts.yaml

PLAY [Create local user accounts on VyOS switches] *****************************
META: ran handlers

TASK [Configure Local-Admin user] **********************************************
task path: /home/student/Desktop/Project/AddUserAccounts.yaml:10
The full traceback is:
  File "/home/student/.ansible/collections/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/usr/local/lib/python3.8/dist-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [switch4]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "backup_options": null,
            "comment": "configured by vyos_config",
            "config": null,
            "lines": [
                "set system login user Local-Admin authentication plaintext-password 'WGU123'",
                "set system login user Local-Admin level 15"
            ],
            "match": "line",
            "save": true,
            "src": null
        }
    },
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
The full traceback is:
  File "/home/student/.ansible/collections/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/usr/local/lib/python3.8/dist-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [switch1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "backup_options": null,
            "comment": "configured by vyos_config",
            "config": null,
            "lines": [
                "set system login user Local-Admin authentication plaintext-password 'WGU123'",
                "set system login user Local-Admin level 15"
            ],
            "match": "line",
            "save": true,
            "src": null
        }
    },
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
The full traceback is:
  File "/home/student/.ansible/collections/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/usr/local/lib/python3.8/dist-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [switch2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "backup_options": null,
            "comment": "configured by vyos_config",
            "config": null,
            "lines": [
                "set system login user Local-Admin authentication plaintext-password 'WGU123'",
                "set system login user Local-Admin level 15"
            ],
            "match": "line",
            "save": true,
            "src": null
        }
    },
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
The full traceback is:
  File "/home/student/.ansible/collections/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/usr/local/lib/python3.8/dist-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [switch3]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "backup_options": null,
            "comment": "configured by vyos_config",
            "config": null,
            "lines": [
                "set system login user Local-Admin authentication plaintext-password 'WGU123'",
                "set system login user Local-Admin level 15"
            ],
            "match": "line",
            "save": true,
            "src": null
        }
    },
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
The full traceback is:
  File "/home/student/.ansible/collections/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/vyos.py", line 60, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/usr/local/lib/python3.8/dist-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [switch5]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "backup_options": null,
            "comment": "configured by vyos_config",
            "config": null,
            "lines": [
                "set system login user Local-Admin authentication plaintext-password 'WGU123'",
                "set system login user Local-Admin level 15"
            ],
            "match": "line",
            "save": true,
            "src": null
        }
    },
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}

PLAY RECAP *********************************************************************
switch1                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
switch2                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
switch3                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
switch4                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
switch5                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

student@student-Standard-PC-i440FX-PIIX-1996:~/Desktop/Project$ 
