erInventory.py 
Failed to gather information from Windows1 (10.10.1.10): HTTPConnectionPool(host='10.10.1.10', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc959b46a30>: Failed to establish a new connection: [Errno 113] No route to host'))
Failed to gather information from Windows2 (10.10.1.11): HTTPConnectionPool(host='10.10.1.11', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc959a7e5b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Failed to connect to Linux1 (10.10.1.12): [Errno None] Unable to connect to port 22 on 10.10.1.12
Failed to connect to Linux2 (10.10.1.13): [Errno None] Unable to connect to port 22 on 10.10.1.13
Failed to gather information from TestBox1 (10.10.1.20): HTTPConnectionPool(host='10.10.1.20', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc959a892e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Failed to gather information from TestBox2 (10.10.1.21): HTTPConnectionPool(host='10.10.1.21', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc959a89d30>: Failed to establish a new connection: [Errno 113] No route to host'))
Workstations inventory successfully saved to /home/student/Desktop/Project/workstations_inventory.yaml
